#
# Basic settings.
#
url: https://mtb.kmz-brno.cz
title: MTB
avatar: /assets/img/icon.svg
favicon: /assets/img/icon.ico
author: Jan Horáček
robots: index,follow
baseurl: ""

#
# Icons
#
icons:
  rss: false
  email: jan.horacek@kmz-brno.cz
  github: kmzbrnoI
  bitbucket:
  twitter:
  facebook: kmzbrnoI
  google_plus:
  tumblr:
  behance:
  dribbble:
  flickr:
  instagram:
  linkedin: # full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange: # full URL
  steam:
  wordpress:
  youtube:

#
# Prettify url.
#
permalink: pretty

#
# Plugins.
#
plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-last-modified-at

#
# !! Danger zone !!
#

include: [
    "_pages",
    ".htaccess",
]

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

excerpt_separator: <!--more-->

sass:
  sass_dir: _sass
  style: :compressed # or :expanded

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor
  - Makefile

t:
  en:
    description: "IO bus for model railroad accessories control"
    keywords: io,bus,mtb,module,uni,ttl,protocol
  cz:
    description: "IO sběrnice pro řízení příslušenství modelových kolejišť"
    keywords: io,sběrnice,mtb,modul,uni,ttl,protokol

last-modified-at:
    date-format: '%%y-%b-%d'
